# Final Chatbot: IT Helpdesk Chatbot for NU Students

This notebook builds the text feature-extraction step for an IT Helpdesk chatbot aimed at NU students. It covers Bag of Words and TF-IDF vectorization on the training dataset, then uses the resulting features to train a simple intent-classification chatbot that can respond to common IT support questions (e.g. password resets, wifi/LMS access issues).

In [ ]:
import pandas as pd
import json
import random
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression

DATA_PATH = "."

In [ ]:
# 1. Load the dataset
df = pd.read_csv(f"{DATA_PATH}/training_data.csv")

print("Dataset shape:", df.shape)
print("Number of unique intents:", df["intent"].nunique())
df.head()

Dataset shape: (509, 2)
Number of unique intents: 41

               text    intent
0                Hi  greeting
1      How are you?  greeting
2  Is anyone there?  greeting
3             Hello  greeting
4          Good day  greeting

In [ ]:
#handles slang queries

normalization_dict = {
    "abt": "about", "u": "you", "ur": "your", "pls": "please", "plz": "please",
    "thx": "thanks", "tnx": "thanks", "info": "information", "san": "saan",
    "kelan": "kailan", "d2": "dito", "b4": "before", "asap": "as soon as possible",
    "yr": "your", "msg": "message", "acc": "account", "reg": "registration",
    "wla": "wala", "pano": "paano", "cge": "sige",
    "gud": "good", "gud am": "good morning", "gud pm": "good afternoon"
}

def normalize_text(text):
    text = text.lower()
    words = text.split()
    normalized_words = [normalization_dict.get(w, w) for w in words]
    return " ".join(normalized_words)

df["text"] = df["text"].apply(normalize_text)
df.head()

               text    intent
0                hi  greeting
1      how are you?  greeting
2  is anyone there?  greeting
3             hello  greeting
4          good day  greeting

In [ ]:
#Bag of Words Model

count_vectorizer = CountVectorizer()
X_counts = count_vectorizer.fit_transform(df["text"])

print("Vocabulary:")
print(count_vectorizer.vocabulary_)

print("\nMatrix shape:", X_counts.shape)

bow_df = pd.DataFrame(X_counts.toarray(), columns=count_vectorizer.get_feature_names_out())
print("\nFirst five rows:")
bow_df.head()

Vocabulary:
{'hi': 164, 'how': 172, 'are': 27, 'you': 425, 'is': 186, 'anyone': 24, 'there': 372, 'hello': 160, 'good': 146, 'day': 91, 'what': 409, 'up': 396, 'ya': 423, 'heyy': 163, 'whatsup': 411, 'po': 301, 'kumusta': 202, 'magandang': 225, 'araw': 26, 'uy': 398, 'pwede': 310, 'magtanong': 229, 'cya': 89, 'see': 338, 'bye': 56, 'later': 208, 'goodbye': 147, 'am': 16, 'leaving': 210, 'have': 156, 'talk': 363, 'to': 383, 'ttyl': 387, 'got': 148, 'go': 145, 'gtg': 151, 'sige': 345, 'salamat': 327, 'ok': 274, 'thank': 369, 'aalis': 0, 'na': 253, 'ako': 14, 'paalam': 287, 'name': 255, 'your': 426, 'do': 100, 'called': 59, 'should': 344, 'call': 58, 'whats': 410, 'who': 417, 'this': 377, 'chatting': 69, 'taking': 362, 'ano': 20, 'pangalan': 293, 'mo': 248, 'sino': 346, 'ka': 192, 'meron': 245, 'bang': 39, 'timing': 380, 'of': 269, 'college': 76, 'working': 422, 'days': 92, 'when': 413, 'guys': 153, 'open': 280, 'hours': 171, 'operation': 281, 'the': 371, 'about': 1, 'on': 278, 'saturday': 329, 'tell': 368, 'something': 348, 'come': 77, 'attend': 30, 'my': 252, 'time': 378, 'anong': 21, 'oras': 284, 'bukas': 54, 'ang': 19, 'opisina': 282, 'hanggang': 155, 'kailan': 193, 'school': 333, 'sarado': 328, 'office': 272, 'more': 250, 'information': 180, 'contact': 85, 'telephone': 367, 'number': 268, 'no': 264, 'phone': 298, 'can': 61, 'get': 142, 'ng': 261, 'paano': 288, 'ko': 198, 'kayo': 196, 'matatawagan': 237, 'tawagan': 365, 'list': 215, 'courses': 88, 'offered': 271, 'in': 178, 'univrsity': 395, 'uni': 391, 'offer': 270, 'branches': 50, 'available': 32, 'at': 29, 'me': 242, 'computer': 82, 'engineering': 116, 'it': 188, 'technology': 366, 'ai': 13, 'ml': 247, 'mechanical': 243, 'chemical': 71, 'civil': 72, 'mga': 246, 'kurso': 204, 'course': 87, 'kunin': 203, 'programs': 306, 'fee': 127, 'per': 297, 'semester': 340, 'each': 111, 'fees': 128, 'year': 424, 'much': 251, 'for': 135, 'first': 130, 'hostel': 170, 'ac': 2, 'room': 323, 'non': 265, 'girls': 143, 'boys': 48, 'magkano': 227, 'tuition': 388, 'magbayad': 226, 'saan': 325, 'installment': 182, 'bayad': 41, 'where': 414, 'located': 217, 'address': 9, 'reach': 312, 'location': 218, 'wheres': 415, 'nu': 267, 'laguna': 205, 'campus': 60, 'pumunta': 309, 'dun': 109, 'facility': 125, 'servive': 342, 'facilities': 124, 'does': 103, 'provide': 307, 'any': 23, 'capacity': 64, 'far': 126, 'from': 138, 'distance': 98, 'big': 45, 'between': 43, 'and': 18, 'may': 241, 'dorm': 105, 'ba': 36, 'tirahan': 382, 'sa': 324, 'mag': 224, 'apply': 25, 'events': 121, 'organised': 285, 'conducted': 83, 'event': 120, 'held': 159, 'functions': 139, 'ngayon': 262, 'activity': 7, 'week': 407, 'susunod': 357, 'document': 101, 'bring': 52, 'documents': 102, 'needed': 258, 'admision': 10, 'admission': 11, 'during': 110, 'required': 319, 'which': 416, 'need': 257, 'requirements': 320, 'kailangan': 194, 'kumuha': 201, 'tor': 384, 'request': 318, 'size': 347, 'building': 53, 'many': 236, 'floors': 132, 'tall': 364, 'saang': 326, 'floor': 131, 'library': 213, 'nasa': 256, 'second': 337, 'registrar': 315, 'syllabus': 358, 'timetable': 379, 'next': 260, 'lecture': 211, 'makuha': 233, 'online': 279, 'books': 47, 'book': 46, 'libraries': 212, 'mangutang': 235, 'libro': 214, 'yung': 427, 'lrc': 223, 'infrastructure': 181, 'gym': 154, 'dito': 99, 'food': 133, 'canteen': 63, 'cafetaria': 57, 'kumain': 199, 'menu': 244, 'foods': 134, 'we': 405, 'variety': 401, 'eat': 112, 'pagkain': 292, 'placement': 299, 'companies': 80, 'visit': 404, 'average': 33, 'package': 289, 'recruitment': 313, 'tulong': 389, 'paghahanap': 291, 'trabaho': 385, 'ojt': 273, 'hod': 167, 'head': 158, 'chairperson': 68, 'department': 94, 'science': 334, 'extc': 123, 'ece': 113, 'principal': 304, 'whatv': 412, 'exam': 122, 'dates': 90, 'schedule': 330, 'sem': 339, 'magsisimula': 228, 'ilang': 177, 'units': 393, 'bawat': 40, 'process': 305, 'take': 360, 'pag': 290, 'enroll': 117, 'pa': 286, 'scholarship': 331, 'ce': 67, 'scholarships': 332, 'comps': 81, 'automobile': 31, 'third': 376, 'fourth': 137, 'iskolarship': 187, 'provided': 308, 'pasilidad': 294, 'max': 239, 'students': 353, 'seats': 336, 'branch': 49, 'maximum': 240, 'intake': 183, 'stundent': 354, 'taken': 361, 'seat': 335, 'allotment': 15, 'ilan': 176, 'estudyante': 119, 'tinatanggap': 381, 'dress': 106, 'code': 75, 'dresscode': 107, 'uniform': 392, 'wear': 406, 'casuals': 66, 'an': 17, 'bibili': 44, 'different': 97, 'committe': 78, 'committee': 79, 'give': 144, 'details': 95, 'holidays': 169, 'will': 420, 'starts': 350, 'end': 115, 'holiday': 168, 'these': 373, 'vacations': 400, 'vacation': 399, 'long': 222, 'be': 42, 'bakasyon': 37, 'semestral': 341, 'break': 51, 'sports': 349, 'games': 140, 'activities': 6, 'please': 300, 'varsity': 402, 'okk': 277, 'okie': 276, 'nice': 263, 'work': 421, 'well': 408, 'done': 104, 'job': 190, 'thanks': 370, 'help': 161, 'its': 189, 'okay': 275, 'ayos': 35, 'thing': 374, 'things': 375, 'why': 418, 'use': 397, 'kaya': 195, 'mong': 249, 'gawin': 141, 'ibigay': 174, 'ragging': 311, 'practice': 303, 'active': 5, 'antiragging': 22, 'cases': 65, 'here': 162, 'against': 12, 'juniors': 191, 'history': 166, 'incidents': 179, 'hazing': 157, 'report': 317, 'bullying': 55, 'log': 220, 'into': 185, 'student': 352, 'portal': 302, 'forgot': 136, 'password': 296, 'reset': 321, 'cant': 62, 'access': 3, 'if': 175, 'account': 4, 'locked': 219, 'login': 221, 'nakalimutan': 254, 'hindi': 165, 'makapasok': 230, 'connect': 84, 'wifi': 419, 'university': 394, 'internet': 184, 'not': 266, 'network': 259, 'kumonekta': 200, 'bakit': 38, 'ayaw': 34, 'classes': 74, 'find': 129, 'materials': 238, 'learning': 209, 'management': 234, 'system': 359, 'class': 73, 'lms': 216, 'submit': 356, 'assignment': 28, 'makita': 232, 'klase': 197, 'di': 96, 'subject': 355, 'set': 343, 'email': 114, 'gumagana': 152, 'check': 70, 'grades': 150, 'results': 322, 'view': 403, 'transcript': 386, 'released': 316, 'copy': 86, 'grade': 149, 'makikita': 231, 'lalabas': 206, 'pasok': 295, 'register': 314, 'deadline': 93, 'enrollment': 118, 'add': 8, 'or': 283, 'drop': 108, 'still': 351, 'late': 207, 'ulit': 390, 'huling': 173}

Matrix shape: (509, 428)

First five rows:

,aalis,about,ac,access,account,active,activities,activity,add,address,...,why,wifi,will,work,working,ya,year,you,your,yung
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#TF-IDF

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(df["text"])

print("Vocabulary:")
print(tfidf_vectorizer.vocabulary_)

print("\nMatrix shape:", X_tfidf.shape)

tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
print("\nFirst five rows:")
tfidf_df.head()

Vocabulary:
{'hi': 164, 'how': 172, 'are': 27, 'you': 425, 'is': 186, 'anyone': 24, 'there': 372, 'hello': 160, 'good': 146, 'day': 91, 'what': 409, 'up': 396, 'ya': 423, 'heyy': 163, 'whatsup': 411, 'po': 301, 'kumusta': 202, 'magandang': 225, 'araw': 26, 'uy': 398, 'pwede': 310, 'magtanong': 229, 'cya': 89, 'see': 338, 'bye': 56, 'later': 208, 'goodbye': 147, 'am': 16, 'leaving': 210, 'have': 156, 'talk': 363, 'to': 383, 'ttyl': 387, 'got': 148, 'go': 145, 'gtg': 151, 'sige': 345, 'salamat': 327, 'ok': 274, 'thank': 369, 'aalis': 0, 'na': 253, 'ako': 14, 'paalam': 287, 'name': 255, 'your': 426, 'do': 100, 'called': 59, 'should': 344, 'call': 58, 'whats': 410, 'who': 417, 'this': 377, 'chatting': 69, 'taking': 362, 'ano': 20, 'pangalan': 293, 'mo': 248, 'sino': 346, 'ka': 192, 'meron': 245, 'bang': 39, 'timing': 380, 'of': 269, 'college': 76, 'working': 422, 'days': 92, 'when': 413, 'guys': 153, 'open': 280, 'hours': 171, 'operation': 281, 'the': 371, 'about': 1, 'on': 278, 'saturday': 329, 'tell': 368, 'something': 348, 'come': 77, 'attend': 30, 'my': 252, 'time': 378, 'anong': 21, 'oras': 284, 'bukas': 54, 'ang': 19, 'opisina': 282, 'hanggang': 155, 'kailan': 193, 'school': 333, 'sarado': 328, 'office': 272, 'more': 250, 'information': 180, 'contact': 85, 'telephone': 367, 'number': 268, 'no': 264, 'phone': 298, 'can': 61, 'get': 142, 'ng': 261, 'paano': 288, 'ko': 198, 'kayo': 196, 'matatawagan': 237, 'tawagan': 365, 'list': 215, 'courses': 88, 'offered': 271, 'in': 178, 'univrsity': 395, 'uni': 391, 'offer': 270, 'branches': 50, 'available': 32, 'at': 29, 'me': 242, 'computer': 82, 'engineering': 116, 'it': 188, 'technology': 366, 'ai': 13, 'ml': 247, 'mechanical': 243, 'chemical': 71, 'civil': 72, 'mga': 246, 'kurso': 204, 'course': 87, 'kunin': 203, 'programs': 306, 'fee': 127, 'per': 297, 'semester': 340, 'each': 111, 'fees': 128, 'year': 424, 'much': 251, 'for': 135, 'first': 130, 'hostel': 170, 'ac': 2, 'room': 323, 'non': 265, 'girls': 143, 'boys': 48, 'magkano': 227, 'tuition': 388, 'magbayad': 226, 'saan': 325, 'installment': 182, 'bayad': 41, 'where': 414, 'located': 217, 'address': 9, 'reach': 312, 'location': 218, 'wheres': 415, 'nu': 267, 'laguna': 205, 'campus': 60, 'pumunta': 309, 'dun': 109, 'facility': 125, 'servive': 342, 'facilities': 124, 'does': 103, 'provide': 307, 'any': 23, 'capacity': 64, 'far': 126, 'from': 138, 'distance': 98, 'big': 45, 'between': 43, 'and': 18, 'may': 241, 'dorm': 105, 'ba': 36, 'tirahan': 382, 'sa': 324, 'mag': 224, 'apply': 25, 'events': 121, 'organised': 285, 'conducted': 83, 'event': 120, 'held': 159, 'functions': 139, 'ngayon': 262, 'activity': 7, 'week': 407, 'susunod': 357, 'document': 101, 'bring': 52, 'documents': 102, 'needed': 258, 'admision': 10, 'admission': 11, 'during': 110, 'required': 319, 'which': 416, 'need': 257, 'requirements': 320, 'kailangan': 194, 'kumuha': 201, 'tor': 384, 'request': 318, 'size': 347, 'building': 53, 'many': 236, 'floors': 132, 'tall': 364, 'saang': 326, 'floor': 131, 'library': 213, 'nasa': 256, 'second': 337, 'registrar': 315, 'syllabus': 358, 'timetable': 379, 'next': 260, 'lecture': 211, 'makuha': 233, 'online': 279, 'books': 47, 'book': 46, 'libraries': 212, 'mangutang': 235, 'libro': 214, 'yung': 427, 'lrc': 223, 'infrastructure': 181, 'gym': 154, 'dito': 99, 'food': 133, 'canteen': 63, 'cafetaria': 57, 'kumain': 199, 'menu': 244, 'foods': 134, 'we': 405, 'variety': 401, 'eat': 112, 'pagkain': 292, 'placement': 299, 'companies': 80, 'visit': 404, 'average': 33, 'package': 289, 'recruitment': 313, 'tulong': 389, 'paghahanap': 291, 'trabaho': 385, 'ojt': 273, 'hod': 167, 'head': 158, 'chairperson': 68, 'department': 94, 'science': 334, 'extc': 123, 'ece': 113, 'principal': 304, 'whatv': 412, 'exam': 122, 'dates': 90, 'schedule': 330, 'sem': 339, 'magsisimula': 228, 'ilang': 177, 'units': 393, 'bawat': 40, 'process': 305, 'take': 360, 'pag': 290, 'enroll': 117, 'pa': 286, 'scholarship': 331, 'ce': 67, 'scholarships': 332, 'comps': 81, 'automobile': 31, 'third': 376, 'fourth': 137, 'iskolarship': 187, 'provided': 308, 'pasilidad': 294, 'max': 239, 'students': 353, 'seats': 336, 'branch': 49, 'maximum': 240, 'intake': 183, 'stundent': 354, 'taken': 361, 'seat': 335, 'allotment': 15, 'ilan': 176, 'estudyante': 119, 'tinatanggap': 381, 'dress': 106, 'code': 75, 'dresscode': 107, 'uniform': 392, 'wear': 406, 'casuals': 66, 'an': 17, 'bibili': 44, 'different': 97, 'committe': 78, 'committee': 79, 'give': 144, 'details': 95, 'holidays': 169, 'will': 420, 'starts': 350, 'end': 115, 'holiday': 168, 'these': 373, 'vacations': 400, 'vacation': 399, 'long': 222, 'be': 42, 'bakasyon': 37, 'semestral': 341, 'break': 51, 'sports': 349, 'games': 140, 'activities': 6, 'please': 300, 'varsity': 402, 'okk': 277, 'okie': 276, 'nice': 263, 'work': 421, 'well': 408, 'done': 104, 'job': 190, 'thanks': 370, 'help': 161, 'its': 189, 'okay': 275, 'ayos': 35, 'thing': 374, 'things': 375, 'why': 418, 'use': 397, 'kaya': 195, 'mong': 249, 'gawin': 141, 'ibigay': 174, 'ragging': 311, 'practice': 303, 'active': 5, 'antiragging': 22, 'cases': 65, 'here': 162, 'against': 12, 'juniors': 191, 'history': 166, 'incidents': 179, 'hazing': 157, 'report': 317, 'bullying': 55, 'log': 220, 'into': 185, 'student': 352, 'portal': 302, 'forgot': 136, 'password': 296, 'reset': 321, 'cant': 62, 'access': 3, 'if': 175, 'account': 4, 'locked': 219, 'login': 221, 'nakalimutan': 254, 'hindi': 165, 'makapasok': 230, 'connect': 84, 'wifi': 419, 'university': 394, 'internet': 184, 'not': 266, 'network': 259, 'kumonekta': 200, 'bakit': 38, 'ayaw': 34, 'classes': 74, 'find': 129, 'materials': 238, 'learning': 209, 'management': 234, 'system': 359, 'class': 73, 'lms': 216, 'submit': 356, 'assignment': 28, 'makita': 232, 'klase': 197, 'di': 96, 'subject': 355, 'set': 343, 'email': 114, 'gumagana': 152, 'check': 70, 'grades': 150, 'results': 322, 'view': 403, 'transcript': 386, 'released': 316, 'copy': 86, 'grade': 149, 'makikita': 231, 'lalabas': 206, 'pasok': 295, 'register': 314, 'deadline': 93, 'enrollment': 118, 'add': 8, 'or': 283, 'drop': 108, 'still': 351, 'late': 207, 'ulit': 390, 'huling': 173}

Matrix shape: (509, 428)

First five rows:

,aalis,about,ac,access,account,active,activities,activity,add,address,...,why,wifi,will,work,working,ya,year,you,your,yung
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.576273,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [ ]:
sorted_vocab = sorted(count_vectorizer.vocabulary_.keys())
print("Sample of vocabulary (first 20 words):")
print(sorted_vocab[:20])

Sample of vocabulary (first 20 words):
['aalis', 'about', 'ac', 'access', 'account', 'active', 'activities', 'activity', 'add', 'address', 'admision', 'admission', 'against', 'ai', 'ako', 'allotment', 'am', 'an', 'and', 'ang']

#Testing the Chatbot

In [ ]:
#uses TF-IDF
model = LogisticRegression(max_iter=1000)
model.fit(X_tfidf, df["intent"])

print("Model trained on", X_tfidf.shape[0], "examples across", df["intent"].nunique(), "intents")

Model trained on 509 examples across 41 intents

In [ ]:
with open(f"{DATA_PATH}/intents_merged.json") as f:
    intents_data = json.load(f)

#looks up possible responses
response_lookup = {intent["tag"]: intent["responses"] for intent in intents_data["intents"]}

In [ ]:
MIN_GAP = 0.03

while True:
    user_input = input("You: ")
    if user_input.lower() in ["quit", "exit"]:
        print("Bot: Bye! Ingat.")
        break

    cleaned_input = normalize_text(user_input)
    input_vector = tfidf_vectorizer.transform([cleaned_input])

    probabilities = model.predict_proba(input_vector)[0]
    sorted_indices = probabilities.argsort()[::-1]
    best_index = sorted_indices[0]
    second_index = sorted_indices[1]

    best_intent = model.classes_[best_index]
    confidence = probabilities[best_index]
    gap = confidence - probabilities[second_index]

    if gap < MIN_GAP:
        print("Bot: Sorry, I don't understand. Can you rephrase that?")
    else:
        reply = random.choice(response_lookup[best_intent])
        print(f"Bot: {reply}")
        print(f"      (matched intent: {best_intent}, confidence: {confidence:.2f}, gap: {gap:.2f})")

You: timetable?
Bot: Sorry, I don't understand. Can you rephrase that?
You: quit
Bot: Bye! Ingat.